name: biztory_datavault
profile: default
version: '5.0.0'
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
seed-paths:
  - seeds
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
  load_date: '1992-01-08'
  tpch_size: 10 #1, 10, 100, 1000, 10000

models:
  biztory_datavault:
    staging:
      materialized: view
      +schema: staging
      tags:
        - 'staging'
        - 'stg'
    meta_vault:
      materialized: incremental
      +schema: dbt
      tags:
        - 'meta_vault'
        - 'mv'
    raw_vault:
      materialized: incremental
      +schema: raw_vault
      tags:
        - 'raw_vault'
        - 'rv'
    business_vault:
      materialised: view
      +schema: business_vault
      tags:
        - 'business_vault'
        - 'bv'
    information_vault:
      materialised: view
      tags:
        - 'information_vault'
        - 'iv'